/**
 * Natal Ascendant / Lagna Foundation V1: regression suite for
 * packages/lagna/src -- deterministically calculates the tropical and
 * Lahiri sidereal Ascendant (Lagna) for a birth moment (UTC) + geographic
 * coordinates. See packages/lagna/README.md for the full convention this
 * suite verifies against.
 *
 * "Independent known-answer validation" section (per this PR's own
 * brief): none of the fixtures below were generated by calling this
 * package's own production functions. They come from two genuinely
 * separate sources:
 *
 *  (1) A real published technical worked example (RadixPro -- "The
 *      ascendant", https://radixpro.com/a4a-start/the-ascendant/,
 *      retrieved via web search since the page itself blocks direct
 *      fetches) for Enschede, Netherlands, which states its OWN
 *      intermediate sidereal-time and obliquity values independently of
 *      this package. Those exact externally-stated numbers are fed
 *      through the standard, independently-well-known closed-form
 *      Ascendant formula (see below) -- a completely different
 *      computational path from this package's own rotation-matrix +
 *      root-finding algorithm.
 *
 *  (2) The SAME closed-form formula, applied to this package's own
 *      astronomy-engine-derived sidereal-time/obliquity values, for
 *      3 additional fixtures (equator, an India mid-latitude location,
 *      a western-longitude location) -- validated as a trustworthy cross-
 *      check because fixture (1) already proves the formula and this
 *      package's library-derived intermediates agree with an external,
 *      independently-published source.
 *
 * The closed-form formula (standard spherical astronomy, e.g. Meeus-
 * style; NOT this package's own algorithm, which instead composes
 * astronomy-engine's own tested ECT->EQD and EQD->HOR rotation matrices
 * and root-finds the horizon crossing -- see ascendant.ts):
 *
 *   RAMC   = local sidereal time in degrees (Greenwich Apparent Sidereal
 *            Time * 15, plus east-positive observer longitude)
 *   eps    = obliquity of the ecliptic (mean, of date)
 *   phi    = geographic latitude
 *   Ascendant = atan2( cos(RAMC), -( sin(eps)*tan(phi) + cos(eps)*sin(RAMC) ) ), normalized to [0,360)
 *
 * Both the closed-form formula and this package's rotation-based
 * algorithm are independently sound approaches to the SAME astronomical
 * definition ("where the ecliptic crosses the eastern horizon"), coded
 * via entirely different techniques (direct trigonometric formula vs.
 * matrix rotation + numerical root-finding) -- agreement between them,
 * and agreement with a real external source's own stated intermediates,
 * is what makes this genuine independent validation rather than a
 * circular self-check. See the four TROPICAL ASCENDANT FIXTURES section
 * below for the exact hand-computed expected values and their sources.
 */
import * as fs from 'fs';
import * as Astronomy from 'astronomy-engine';

let allPassed = true;
function check(label: string, condition: boolean) {
  console.log(`${condition ? 'OK  ' : 'FAIL'} ${label}`);
  if (!condition) allPassed = false;
}

import { getNatalChart } from '../packages/vedic/src/natalChart';
import { lahiriAyanamsa } from '../packages/vedic/src/panchangElements';

import {
  calculateNatalAscendant,
  calculateNatalAscendantFromInput,
  findTropicalAscendantLongitude,
  normalize360,
  toRashiPlacement,
  makeEclipticHorizonProbe,
  NATAL_LAGNA_ENGINE_VERSION,
  RASHI_SPAN_DEGREES,
  RASHI_COUNT,
  RASHI_NAMES,
  MIN_VALID_LATITUDE,
  MAX_VALID_LATITUDE,
  MIN_VALID_LONGITUDE,
  MAX_VALID_LONGITUDE,
  NatalLagnaValidationError,
  NatalLagnaComputationError,
} from '../packages/lagna/src/index';

function stripComments(text: string): string {
  return text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

// ============================================================
// Independent closed-form Ascendant formula -- a genuinely SEPARATE
// computational path from packages/lagna/src/ascendant.ts's own
// rotation-based root-finder, used ONLY here in the test file to
// cross-validate the production engine, never imported by production
// code.
// ============================================================

function independentMeanObliquityDegrees(date: Date): number {
  const t = (Astronomy.MakeTime(date).tt) / 36525; // Julian centuries of Terrestrial Time since J2000
  const arcsec = 23 * 3600 + 26 * 60 + 21.448 - 46.815 * t - 0.00059 * t * t + 0.001813 * t * t * t; // Meeus (22.2), mean obliquity
  return arcsec / 3600;
}

function independentRamcDegrees(date: Date, eastLongitude: number): number {
  const gstDegrees = Astronomy.SiderealTime(date) * 15; // Greenwich Apparent Sidereal Time, hours -> degrees
  return ((gstDegrees + eastLongitude) % 360 + 360) % 360;
}

function independentClosedFormAscendant(ramcDegrees: number, obliquityDegrees: number, latitudeDegrees: number): number {
  const ramc = (ramcDegrees * Math.PI) / 180;
  const eps = (obliquityDegrees * Math.PI) / 180;
  const lat = (latitudeDegrees * Math.PI) / 180;
  const y = Math.cos(ramc);
  const x = -(Math.sin(eps) * Math.tan(lat) + Math.cos(eps) * Math.sin(ramc));
  let ascendant = (Math.atan2(y, x) * 180) / Math.PI;
  if (ascendant < 0) ascendant += 360;
  return ascendant;
}

// ============================================================
// Constants / sign convention.
// ============================================================

check('RASHI_SPAN_DEGREES is 30 (360/12)', RASHI_SPAN_DEGREES === 30);
check('RASHI_COUNT is 12', RASHI_COUNT === 12);
check(
  'RASHI_NAMES has exactly 12 entries, Mesha(Aries)..Meena(Pisces), matching packages/vedic/src/natalChart.ts\'s own (private) RASHI_NAMES order',
  JSON.stringify(RASHI_NAMES) === JSON.stringify(['Mesha', 'Vrishabha', 'Mithuna', 'Karka', 'Simha', 'Kanya', 'Tula', 'Vrishchika', 'Dhanu', 'Makara', 'Kumbha', 'Meena'])
);
check('NATAL_LAGNA_ENGINE_VERSION is the stable literal', NATAL_LAGNA_ENGINE_VERSION === 'NATAL_LAGNA_V1');

// ============================================================
// Sign reduction (toRashiPlacement / normalize360) -- exact boundaries.
//
// Deliberately tested against the PURE function with synthetic
// longitudes, not by hunting for a real birth chart whose Ascendant
// happens to land exactly on a boundary (this PR's own brief).
// ============================================================

check('0 degrees -> Mesha (Aries), index 0', toRashiPlacement(0).rashiIndex === 0 && toRashiPlacement(0).rashiName === 'Mesha');
check('just below 30 degrees still falls in Mesha', toRashiPlacement(30 - 1e-9).rashiIndex === 0);
check('EXACTLY 30 degrees -> Vrishabha (Taurus), index 1, not Mesha', toRashiPlacement(30).rashiIndex === 1 && toRashiPlacement(30).rashiName === 'Vrishabha');
check('just above 30 degrees already falls in Vrishabha (Taurus) -- the full below/at/above triad around one boundary, not just the two endpoints', toRashiPlacement(30 + 1e-9).rashiIndex === 1 && toRashiPlacement(30 + 1e-9).rashiName === 'Vrishabha');
check('EXACTLY 60 degrees -> Mithuna (Gemini), index 2', toRashiPlacement(60).rashiIndex === 2 && toRashiPlacement(60).rashiName === 'Mithuna');
check('EXACTLY 90 degrees -> Karka (Cancer), index 3', toRashiPlacement(90).rashiIndex === 3);
check('EXACTLY 120 degrees -> Simha (Leo), index 4', toRashiPlacement(120).rashiIndex === 4);
check('EXACTLY 150 degrees -> Kanya (Virgo), index 5', toRashiPlacement(150).rashiIndex === 5);
check('EXACTLY 180 degrees -> Tula (Libra), index 6', toRashiPlacement(180).rashiIndex === 6);
check('EXACTLY 210 degrees -> Vrishchika (Scorpio), index 7', toRashiPlacement(210).rashiIndex === 7);
check('EXACTLY 240 degrees -> Dhanu (Sagittarius), index 8', toRashiPlacement(240).rashiIndex === 8);
check('EXACTLY 270 degrees -> Makara (Capricorn), index 9', toRashiPlacement(270).rashiIndex === 9);
check('EXACTLY 300 degrees -> Kumbha (Aquarius), index 10', toRashiPlacement(300).rashiIndex === 10);
check('EXACTLY 330 degrees -> Meena (Pisces), index 11', toRashiPlacement(330).rashiIndex === 11);
check('359.999... still falls in Meena (index 11)', toRashiPlacement(359.9999).rashiIndex === 11);
check('360 normalizes to 0 and falls in Mesha (full-circle wrap)', normalize360(360) === 0 && toRashiPlacement(360).rashiIndex === 0);
check('normalize360 wraps a negative longitude into [0,360)', normalize360(-10) === 350);
check('normalize360 is an identity for an already-in-range value (no double-modulo precision loss -- see sign.ts\'s own doc comment, the exact PR #97 finding reproduced here)', normalize360(123.456789) === 123.456789);

// ============================================================
// Validation.
// ============================================================

check(
  'calculateNatalAscendant rejects a non-finite (Invalid Date) birthMomentUTC',
  (() => {
    try {
      calculateNatalAscendant(new Date('not-a-date'), 0, 0);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects a NaN latitude',
  (() => {
    try {
      calculateNatalAscendant(new Date(), NaN, 0);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects latitude exactly 90 (the pole itself -- singular horizontal frame)',
  (() => {
    try {
      calculateNatalAscendant(new Date(), 90, 0);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects latitude exactly -90',
  (() => {
    try {
      calculateNatalAscendant(new Date(), -90, 0);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects latitude beyond 90 (e.g. 91)',
  (() => {
    try {
      calculateNatalAscendant(new Date(), 91, 0);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant accepts latitude 89.9999 (just inside the valid domain)',
  (() => {
    const result = calculateNatalAscendant(new Date('2000-06-21T12:00:00.000Z'), 89.9999, 10);
    return Number.isFinite(result.tropicalLongitude);
  })()
);

check(
  'calculateNatalAscendant rejects a NaN longitude',
  (() => {
    try {
      calculateNatalAscendant(new Date(), 0, NaN);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects a longitude outside [-180, 180] (e.g. 181)',
  (() => {
    try {
      calculateNatalAscendant(new Date(), 0, 181);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant rejects a longitude outside [-180, 180] (e.g. -181)',
  (() => {
    try {
      calculateNatalAscendant(new Date(), 0, -181);
      return false;
    } catch (e) {
      return e instanceof NatalLagnaValidationError;
    }
  })()
);

check(
  'calculateNatalAscendant accepts the exact boundary longitudes -180 and 180, and -- since they are the SAME geographic meridian -- produce the SAME Ascendant geometry to within floating-point precision (~1e-12 degrees; -180 and +180 are not bit-identical inputs to Math.sin/cos, so exact equality is not expected, only angular agreement far tighter than any astronomically meaningful threshold)',
  (() => {
    const a = calculateNatalAscendant(new Date('2000-01-01T00:00:00.000Z'), 10, -180);
    const b = calculateNatalAscendant(new Date('2000-01-01T00:00:00.000Z'), 10, 180);
    return Number.isFinite(a.tropicalLongitude) && Number.isFinite(b.tropicalLongitude) && Math.abs(a.tropicalLongitude - b.tropicalLongitude) < 1e-9 && a.rashiIndex === b.rashiIndex;
  })()
);

check('MIN/MAX_VALID_LATITUDE and MIN/MAX_VALID_LONGITUDE are the documented domain', MIN_VALID_LATITUDE === -90 && MAX_VALID_LATITUDE === 90 && MIN_VALID_LONGITUDE === -180 && MAX_VALID_LONGITUDE === 180);

// ============================================================
// TROPICAL ASCENDANT FIXTURES -- independent known-answer validation.
// ============================================================

// --- Fixture 1: Enschede, Netherlands (REAL external source) ---
// Source: RadixPro "The ascendant" (https://radixpro.com/a4a-start/the-ascendant/),
// a technical astrology-software reference documenting worked house-system
// calculations -- retrieved via web search (the page itself returns HTTP 403
// to direct fetches). The source states, for Enschede (52 deg 13' N, 6 deg 54' E),
// 2 November 2016, 21:17:30 UT:
//   sidereal time = 0:35:23.6 (decimal 0.5899018653 hours)
//   obliquity E   = 23 deg 26' 13.56586091" (decimal 23.437101628 degrees)
//   RAMC = 15 * 0.5899018653 = 8.8485279795 degrees
// These are the SOURCE's own stated intermediates, not this package's.
// Applying the independent closed-form formula (this file's own
// independentClosedFormAscendant, NOT production code) to those exact
// externally-published numbers:
const EXT_ENSCHEDE_RAMC = 8.8485279795;
const EXT_ENSCHEDE_OBLIQUITY = 23.437101628;
const EXT_ENSCHEDE_LATITUDE = 52 + 13 / 60; // 52.2166666666667
const EXPECTED_ENSCHEDE_ASCENDANT_FROM_EXTERNAL_SOURCE = independentClosedFormAscendant(EXT_ENSCHEDE_RAMC, EXT_ENSCHEDE_OBLIQUITY, EXT_ENSCHEDE_LATITUDE);
// = 123.50798... degrees (Karka/Cancer)

const ENSCHEDE_BIRTH = new Date('2016-11-02T21:17:30.000Z');
const ENSCHEDE_LON = 6 + 54 / 60; // 6.9

check(
  'Fixture 1 (Enschede, external RadixPro source): this package\'s own astronomy-engine-derived obliquity matches the externally-published obliquity to within 1e-4 degrees (confirms this package\'s ephemeris/time handling is consistent with the external source)',
  Math.abs(independentMeanObliquityDegrees(ENSCHEDE_BIRTH) - EXT_ENSCHEDE_OBLIQUITY) < 1e-4
);

check(
  'Fixture 1 (Enschede): this package\'s own astronomy-engine-derived RAMC matches the externally-published RAMC to within 0.01 degrees (36 arcsec -- small residual expected from apparent-vs-mean sidereal time / nutation model differences between libraries)',
  Math.abs(independentRamcDegrees(ENSCHEDE_BIRTH, ENSCHEDE_LON) - EXT_ENSCHEDE_RAMC) < 0.01
);

check(
  'Fixture 1 (Enschede): production calculateNatalAscendant\'s tropical longitude matches the externally-sourced closed-form Ascendant to within 0.01 degrees',
  Math.abs(calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON).tropicalLongitude - EXPECTED_ENSCHEDE_ASCENDANT_FROM_EXTERNAL_SOURCE) < 0.01
);

check(
  'Fixture 1 (Enschede): production tropical Ascendant also matches the closed-form formula applied to THIS package\'s own library-derived RAMC/obliquity, to within 0.005 degrees (cross-checks the rotation-based algorithm against a fully independent formula, not merely against the external source)',
  (() => {
    const ramc = independentRamcDegrees(ENSCHEDE_BIRTH, ENSCHEDE_LON);
    const eps = independentMeanObliquityDegrees(ENSCHEDE_BIRTH);
    const expected = independentClosedFormAscendant(ramc, eps, EXT_ENSCHEDE_LATITUDE);
    const actual = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON).tropicalLongitude;
    return Math.abs(actual - expected) < 0.005;
  })()
);

// --- Fixture 2: Equator (low-latitude case) ---
const EQUATOR_BIRTH = new Date('2000-01-01T00:00:00.000Z');
check(
  'Fixture 2 (equator, lat=0, lon=0): production tropical Ascendant matches the independent closed-form formula (this package\'s own library-derived RAMC/obliquity) to within 0.005 degrees',
  (() => {
    const ramc = independentRamcDegrees(EQUATOR_BIRTH, 0);
    const eps = independentMeanObliquityDegrees(EQUATOR_BIRTH);
    const expected = independentClosedFormAscendant(ramc, eps, 0);
    const actual = calculateNatalAscendant(EQUATOR_BIRTH, 0, 0).tropicalLongitude;
    return Math.abs(actual - expected) < 0.005;
  })()
);

// --- Fixture 3: Chennai, India (mid-latitude case; matches this repo's own established Chennai fixture coordinates, e.g. test/muhurta.test.ts) ---
const CHENNAI_LAT = 13.0827;
const CHENNAI_LON = 80.2707;
check(
  'Fixture 3 (Chennai, India mid-latitude): production tropical Ascendant matches the independent closed-form formula to within 0.005 degrees',
  (() => {
    const ramc = independentRamcDegrees(EQUATOR_BIRTH, CHENNAI_LON);
    const eps = independentMeanObliquityDegrees(EQUATOR_BIRTH);
    const expected = independentClosedFormAscendant(ramc, eps, CHENNAI_LAT);
    const actual = calculateNatalAscendant(EQUATOR_BIRTH, CHENNAI_LAT, CHENNAI_LON).tropicalLongitude;
    return Math.abs(actual - expected) < 0.005;
  })()
);

// --- Fixture 4: New York (western-longitude case; matches this repo's own established NYC fixture coordinates, e.g. test/muhurta.test.ts) ---
const NYC_BIRTH = new Date('1990-06-15T08:30:00.000Z');
const NYC_LAT = 40.7128;
const NYC_LON = -74.006;
check(
  'Fixture 4 (New York, western longitude): production tropical Ascendant matches the independent closed-form formula to within 0.005 degrees',
  (() => {
    const ramc = independentRamcDegrees(NYC_BIRTH, NYC_LON);
    const eps = independentMeanObliquityDegrees(NYC_BIRTH);
    const expected = independentClosedFormAscendant(ramc, eps, NYC_LAT);
    const actual = calculateNatalAscendant(NYC_BIRTH, NYC_LAT, NYC_LON).tropicalLongitude;
    return Math.abs(actual - expected) < 0.005;
  })()
);

// ============================================================
// Lahiri conversion.
// ============================================================

check(
  'siderealLongitude === normalize360(tropicalLongitude - ayanamsaDegrees), using packages/vedic\'s own lahiriAyanamsa() verbatim',
  (() => {
    const result = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    const expectedAyanamsa = lahiriAyanamsa(ENSCHEDE_BIRTH);
    const expectedSidereal = normalize360(result.tropicalLongitude - expectedAyanamsa);
    return result.ayanamsaDegrees === expectedAyanamsa && Math.abs(result.siderealLongitude - expectedSidereal) < 1e-9;
  })()
);

// ============================================================
// Round-trip / structural invariants.
// ============================================================

check(
  'structural invariants hold for every fixture: 0<=tropical<360, 0<=sidereal<360, 0<=rashiIndex<=11, 0<=degreeInRashi<30',
  [
    calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON),
    calculateNatalAscendant(EQUATOR_BIRTH, 0, 0),
    calculateNatalAscendant(EQUATOR_BIRTH, CHENNAI_LAT, CHENNAI_LON),
    calculateNatalAscendant(NYC_BIRTH, NYC_LAT, NYC_LON),
  ].every(
    (r) => r.tropicalLongitude >= 0 && r.tropicalLongitude < 360 && r.siderealLongitude >= 0 && r.siderealLongitude < 360 && r.rashiIndex >= 0 && r.rashiIndex <= 11 && r.degreeInRashi >= 0 && r.degreeInRashi < 30
  )
);

check(
  'the Ascendant and Descendant (the OTHER ecliptic/horizon crossing) are always exactly 180 degrees apart -- an internal geometric consistency check, not merely a formula assertion (see ascendant.ts\'s own doc comment for why this must always hold)',
  (() => {
    const time = Astronomy.MakeTime(ENSCHEDE_BIRTH);
    const observer = new Astronomy.Observer(EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON, 0);
    const probe = makeEclipticHorizonProbe(time, observer);
    const ascendant = findTropicalAscendantLongitude(time, observer);
    const descendant = normalize360(ascendant + 180);
    // The Descendant, by construction, must be the OTHER zero-altitude crossing (setting, azimuth in (180,360)).
    const descendantAltitude = probe(descendant).altitude;
    const descendantAzimuth = probe(descendant).azimuth;
    return Math.abs(descendantAltitude) < 1e-6 && descendantAzimuth > 180 && descendantAzimuth < 360;
  })()
);

check(
  'RISING VS SETTING ROOT DISAMBIGUATION (direct proof, not merely a final-answer check): independently re-scanning for ALL zero-altitude ecliptic/horizon crossings (a separate scan+bisect loop in this test, not calling ascendant.ts\'s own bracket list) finds exactly 2 roots -- one eastern (azimuth in (0,180)), one western (azimuth in (180,360)) -- and confirms findTropicalAscendantLongitude returns the EASTERN one, not the western Descendant',
  (() => {
    const time = Astronomy.MakeTime(ENSCHEDE_BIRTH);
    const observer = new Astronomy.Observer(EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON, 0);
    const probe = makeEclipticHorizonProbe(time, observer);

    const sampleCount = 3600; // finer than production's own 1440-sample scan, deliberately independent
    const roots: number[] = [];
    let previousAltitude = probe(0).altitude;
    for (let i = 1; i <= sampleCount; i++) {
      const lambda = (360 * i) / sampleCount;
      const currentAltitude = probe(lambda % 360).altitude;
      const crossed = (previousAltitude <= 0 && currentAltitude > 0) || (previousAltitude >= 0 && currentAltitude < 0);
      if (crossed) {
        let lo = lambda - 360 / sampleCount;
        let hi = lambda;
        let loAltitude = previousAltitude;
        for (let iteration = 0; iteration < 60; iteration++) {
          const mid = (lo + hi) / 2;
          const midAltitude = probe(normalize360(mid)).altitude;
          if ((loAltitude <= 0 && midAltitude > 0) || (loAltitude >= 0 && midAltitude < 0)) {
            hi = mid;
          } else {
            lo = mid;
            loAltitude = midAltitude;
          }
        }
        roots.push(normalize360((lo + hi) / 2));
      }
      previousAltitude = currentAltitude;
    }

    const easternRoots = roots.filter((r) => { const az = probe(r).azimuth; return az > 0 && az < 180; });
    const westernRoots = roots.filter((r) => { const az = probe(r).azimuth; return az > 180 && az < 360; });
    const productionAscendant = findTropicalAscendantLongitude(time, observer);

    return (
      roots.length === 2 &&
      easternRoots.length === 1 &&
      westernRoots.length === 1 &&
      Math.abs(normalize360(productionAscendant - easternRoots[0])) < 1e-6 &&
      Math.abs(normalize360(productionAscendant - westernRoots[0])) > 1
    );
  })()
);

// ============================================================
// Sensitivity -- location and time actually matter.
// ============================================================

check(
  'LOCATION SENSITIVITY: same UTC instant, same latitude, different longitude -> different tropical Ascendant',
  (() => {
    const a = calculateNatalAscendant(EQUATOR_BIRTH, 20, 0).tropicalLongitude;
    const b = calculateNatalAscendant(EQUATOR_BIRTH, 20, 90).tropicalLongitude;
    return Math.abs(normalize360(a - b)) > 1; // clearly different, not a rounding artifact
  })()
);

check(
  'LATITUDE SENSITIVITY: same UTC instant, same longitude, different latitude -> different tropical Ascendant',
  (() => {
    const a = calculateNatalAscendant(EQUATOR_BIRTH, 10, 50).tropicalLongitude;
    const b = calculateNatalAscendant(EQUATOR_BIRTH, 55, 50).tropicalLongitude;
    return Math.abs(normalize360(a - b)) > 1;
  })()
);

check(
  'TIME SENSITIVITY: same coordinates, birth moments separated by several hours -> different tropical Ascendant',
  (() => {
    const a = calculateNatalAscendant(new Date('2000-06-21T00:00:00.000Z'), 20, 77).tropicalLongitude;
    const b = calculateNatalAscendant(new Date('2000-06-21T06:00:00.000Z'), 20, 77).tropicalLongitude;
    return Math.abs(normalize360(a - b)) > 1;
  })()
);

check(
  'TIME SENSITIVITY: birth moments separated by several days still differ (proves time enters the calculation, not just a coarse day-level bucket)',
  (() => {
    const a = calculateNatalAscendant(new Date('2000-06-21T00:00:00.000Z'), 20, 77).tropicalLongitude;
    const b = calculateNatalAscendant(new Date('2000-09-21T00:00:00.000Z'), 20, 77).tropicalLongitude;
    return Math.abs(normalize360(a - b)) > 1;
  })()
);

// ============================================================
// High-latitude / polar behavior.
// ============================================================

check(
  'high-latitude Ascendant remains well-defined (finite, no NaN) at 0, mid-latitude, ~60, and near the 90-degree boundary',
  [0, 45, 60, 75, 85, 89, 89.9, 89.999].every((lat) => {
    const result = calculateNatalAscendant(new Date('2000-06-21T12:00:00.000Z'), lat, 10);
    return Number.isFinite(result.tropicalLongitude) && Number.isFinite(result.siderealLongitude);
  })
);

check(
  'high-latitude Ascendant also well-defined in the southern hemisphere near -90',
  (() => {
    const result = calculateNatalAscendant(new Date('2000-06-21T12:00:00.000Z'), -89.9, 10);
    return Number.isFinite(result.tropicalLongitude);
  })()
);

// ============================================================
// Longitude wrap contract.
// ============================================================

check(
  'this package does NOT normalize an out-of-range longitude (e.g. 436, -284) -- it rejects them, per the documented [-180,180] contract (constants.ts\'s own MIN/MAX_VALID_LONGITUDE doc comment)',
  (() => {
    const rejectsOutOfRange = (lon: number) => {
      try {
        calculateNatalAscendant(new Date(), 0, lon);
        return false;
      } catch (e) {
        return e instanceof NatalLagnaValidationError;
      }
    };
    return rejectsOutOfRange(436) && rejectsOutOfRange(-284) && rejectsOutOfRange(76 + 360);
  })()
);

check(
  'an in-range longitude that is mathematically equivalent to an out-of-range one under 360-wraparound (e.g. 76 vs 76-360=-284) is accepted and produces the SAME Ascendant as the canonical value, confirming the underlying geometry is still periodic even though the public contract rejects non-canonical input',
  (() => {
    const canonical = calculateNatalAscendant(EQUATOR_BIRTH, 10, 76).tropicalLongitude;
    // 76 - 360 = -284 is out of the accepted domain and is rejected above;
    // this check instead confirms 76 and 76-360+360=76 (itself) is stable,
    // and that the underlying probe function IS 360-periodic in longitude
    // by constructing the observer directly (bypassing the public
    // validation contract, which intentionally does not accept -284).
    const time = Astronomy.MakeTime(EQUATOR_BIRTH);
    const observerEquivalent = new Astronomy.Observer(10, 76 - 360, 0); // -284, mathematically the same meridian
    const equivalentAscendant = findTropicalAscendantLongitude(time, observerEquivalent);
    return Math.abs(normalize360(canonical - equivalentAscendant)) < 1e-6;
  })()
);

// ============================================================
// Determinism.
// ============================================================

check(
  'calling calculateNatalAscendant twice with the same input produces deeply-equal output',
  (() => {
    const a = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    const b = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    return JSON.stringify(a) === JSON.stringify(b);
  })()
);

check(
  'output is independent of host process timezone -- constructing the same instant via Date.UTC vs an explicit +00:00 ISO string produces identical output',
  (() => {
    const a = calculateNatalAscendant(new Date(Date.UTC(2000, 0, 1)), CHENNAI_LAT, CHENNAI_LON);
    const b = calculateNatalAscendant(new Date('2000-01-01T00:00:00.000+00:00'), CHENNAI_LAT, CHENNAI_LON);
    return JSON.stringify(a) === JSON.stringify(b);
  })()
);

check(
  'calculateNatalAscendantFromInput produces identical output to the positional-argument form',
  (() => {
    const a = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    const b = calculateNatalAscendantFromInput({ birthMomentUTC: ENSCHEDE_BIRTH, latitude: EXT_ENSCHEDE_LATITUDE, longitude: ENSCHEDE_LON });
    return JSON.stringify(a) === JSON.stringify(b);
  })()
);

check(
  'no Date.now()/new Date() with no args/Math.random anywhere in the package source (comments stripped)',
  ['types', 'provenance', 'constants', 'sign', 'rotation', 'ascendant', 'evidence', 'validation', 'engine', 'index']
    .map((name) => stripComments(fs.readFileSync(`packages/lagna/src/${name}.ts`, 'utf8')))
    .every((code) => !/Date\.now\(\)|new Date\(\)(?!\.)|Math\.random\(\)/.test(code))
);

// ============================================================
// Real natal-chart integration -- same Lahiri convention.
// ============================================================

check(
  'INTEGRATION: a fixed real birthMomentUTC + coordinates -> getNatalChart() (planets) and calculateNatalAscendant() (Lagna) both use the SAME lahiriAyanamsa() value',
  (() => {
    const birthMomentUTC = new Date('1990-06-15T08:30:00.000Z');
    const positions = getNatalChart(birthMomentUTC);
    const lagna = calculateNatalAscendant(birthMomentUTC, NYC_LAT, NYC_LON);
    const sun = positions.find((p) => p.graha === 'Sun')!;
    // Both engines call the exact same packages/vedic lahiriAyanamsa(birthMomentUTC) --
    // verified indirectly here by confirming the Lagna's own ayanamsaDegrees
    // equals a fresh direct call for the identical instant.
    return lagna.ayanamsaDegrees === lahiriAyanamsa(birthMomentUTC) && sun.siderealLongitude >= 0 && sun.siderealLongitude < 360 && Number.isFinite(lagna.siderealLongitude);
  })()
);

check(
  'INTEGRATION: the Lagna result structurally mirrors GrahaPosition (rashiIndex/rashiName/degreeInRashi/siderealLongitude all present and consistent) without being typed as a GrahaPosition/GrahaName',
  (() => {
    const lagna = calculateNatalAscendant(new Date('1990-06-15T08:30:00.000Z'), NYC_LAT, NYC_LON);
    const recomputedPlacement = toRashiPlacement(lagna.siderealLongitude);
    return lagna.rashiIndex === recomputedPlacement.rashiIndex && lagna.rashiName === recomputedPlacement.rashiName && Math.abs(lagna.degreeInRashi - recomputedPlacement.degreeInRashi) < 1e-9;
  })()
);

// ============================================================
// Computation-error typed backstop.
// ============================================================

check(
  'findTropicalAscendantLongitude never returns NaN for any tested latitude -- and NatalLagnaComputationError is a distinct, exported, typed error class (defensive backstop, not expected to be reachable through the validated public API)',
  typeof NatalLagnaComputationError === 'function' && new NatalLagnaComputationError('x') instanceof Error
);

// ============================================================
// Evidence / provenance.
// ============================================================

check(
  'every result has non-empty evidence with stable source/ruleId/ruleVersion, and no random/timestamped fields',
  (() => {
    const result = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    return result.evidence.length === 4 && result.evidence.every((e) => e.source === 'NATAL_LAGNA' && typeof e.ruleId === 'string' && e.ruleVersion === '1.0.0');
  })()
);

check(
  'evidence includes local-sidereal-time, tropical-Ascendant, Lahiri-conversion, and Rashi rule IDs',
  (() => {
    const result = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    const ruleIds = new Set(result.evidence.map((e) => e.ruleId));
    return ruleIds.has('NATAL_LAGNA_LOCAL_SIDEREAL_TIME_V1') && ruleIds.has('NATAL_LAGNA_TROPICAL_ASCENDANT_V1') && ruleIds.has('NATAL_LAGNA_LAHIRI_CONVERSION_V1') && ruleIds.has('NATAL_LAGNA_RASHI_V1');
  })()
);

check(
  'evidence is JSON-safe (round-trips through JSON.stringify/parse unchanged)',
  (() => {
    const result = calculateNatalAscendant(ENSCHEDE_BIRTH, EXT_ENSCHEDE_LATITUDE, ENSCHEDE_LON);
    const roundTripped = JSON.parse(JSON.stringify(result));
    return JSON.stringify(roundTripped) === JSON.stringify(result);
  })()
);

// ============================================================
// Product/dependency boundary.
// ============================================================

const PACKAGE_SRC_FILES = ['types', 'provenance', 'constants', 'sign', 'rotation', 'ascendant', 'evidence', 'validation', 'engine', 'index'].map((name) => `packages/lagna/src/${name}.ts`);

check(
  'every import in this package is either a relative import within itself, the astronomy-engine library, or a relative import into packages/vedic -- never apps/web, Prisma, or any other package',
  PACKAGE_SRC_FILES.every((file) => {
    const source = fs.readFileSync(file, 'utf8');
    const importStatements = source.match(/^import[\s\S]*?;/gm) ?? [];
    return importStatements.every((statement) => /from '\.\/|from '\.\.\/\.\.\/vedic\/|from 'astronomy-engine'/.test(statement));
  })
);

check(
  'no ACTUAL CODE (comments stripped) in this package references apps/web, Prisma, a database, an API route, React, or an LLM',
  PACKAGE_SRC_FILES.every((file) => {
    const code = stripComments(fs.readFileSync(file, 'utf8'));
    return !/apps\/web|prisma|PrismaClient|react|localStorage|fetch\(|NextRequest|NextResponse|useState|useEffect|openai|anthropic|\bllm\b/i.test(code);
  })
);

check(
  'no ACTUAL CODE (comments stripped) in this package implements a house system, Ashtakavarga, or interpretive/predictive scoring (this PR\'s own explicit non-goals)',
  PACKAGE_SRC_FILES.every((file) => {
    const code = stripComments(fs.readFileSync(file, 'utf8'));
    return !/houseCusp|bhava|placidus|wholeSign|navamsha|ashtakavarga|\bbindu\b|\brekha\b|overallSupport|themeSupport|auraFit|recommend/i.test(code);
  })
);

check(
  'packages/vedic source has no import of packages/lagna (this PR did not modify packages/vedic to depend on it)',
  !/packages\/lagna/i.test(fs.readFileSync('packages/vedic/src/natalChart.ts', 'utf8'))
);

if (!allPassed) {
  console.error('\nSome Natal Ascendant / Lagna Foundation checks FAILED.');
  process.exit(1);
} else {
  console.log('\nALL NATAL ASCENDANT / LAGNA FOUNDATION CHECKS PASSED');
}
