ALTER TABLE "User" ADD COLUMN "birthDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "birthTime" TEXT;
ALTER TABLE "User" ADD COLUMN "birthCityName" TEXT;
ALTER TABLE "User" ADD COLUMN "birthLatitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "birthLongitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "birthTimezone" TEXT;
